In [36]:
import utils
import predict
import time as tm
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier as DTC
from sklearn.ensemble import RandomForestClassifier as RFC
from sklearn.datasets import make_classification
import scipy
from sklearn.model_selection import train_test_split

In [37]:
dictSize = 225
(X, y) = utils.loadData( "train", dictSize = dictSize )

In [38]:
X = scipy.sparse.csr_matrix.toarray(X)

In [39]:
# Decision Tree 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
clf_DT = DTC(random_state=0)
op_DT = clf_DT.fit(X_train,y_train)

In [46]:
print (np.size(X_test)/dictSize)
print (y_test)

3300.0
[3. 2. 3. ... 9. 4. 3.]


In [31]:
# Random Forest
clf_RFC = RFC()
op_RFC = clf_RFC.fit(X_train,y_train)

In [66]:
op_Pred_DT = op_DT.predict_proba(X_test)
# top k predictions
k = 20
top_n_pred = np.argsort(-op_Pred_DT,axis=1)[:,:k]
class_labels= clf_DT.classes_
yPred_DT = class_labels[top_n_pred]

In [67]:
# eval functions
preck = utils.getPrecAtK( y_test, yPred_DT, k )
# The macro precision code takes a bit longer to execute due to the for loop over labels
mpreck = utils.getMPrecAtK( y_test, yPred_DT, k )

# According to our definitions, both prec@k and mprec@k should go up as k goes up i.e. for your
# method, prec@i > prec@j if i > j and mprec@i > mprec@j if i > j. See the assignment description
# to convince yourself why this must be the case.

print( "prec@1: %0.3f" % preck[0], "prec@3: %0.3f" % preck[2], "prec@5: %0.3f" % preck[4] )
# Dont be surprised if mprec is small -- it is hard to do well on rare error classes
print( "mprec@1: %0.3e" % mpreck[0], "mprec@3: %0.3e" % mpreck[2], "mprec@5: %0.3e" % mpreck[4] )
print ("prec matrix",preck)
print ("mprec matrix",mpreck)

prec@1: 0.740 prec@3: 0.804 prec@5: 0.805
mprec@1: 5.811e-03 mprec@3: 4.774e-02 mprec@5: 9.941e-02
prec matrix [0.74030303 0.79939394 0.80393939 0.80393939 0.80545455 0.80727273
 0.80878788 0.80909091 0.80939394 0.81       0.81333333 0.81636364
 0.81727273 0.81848485 0.81878788 0.82090909 0.82121212 0.82363636
 0.82424242 0.82666667]
mprec matrix [0.00581107 0.02643503 0.04773651 0.07787835 0.09940824 0.12600399
 0.13284289 0.15411949 0.15635913 0.17539608 0.18451462 0.18451462
 0.20579122 0.21946903 0.25011746 0.26091694 0.2944437  0.3121742
 0.34172503 0.35624715]


In [68]:
print (y_test)
op_DT.predict(X_test)

[3. 2. 3. ... 9. 4. 3.]


array([ 3.,  2.,  3., ...,  9.,  4., 12.])

In [69]:
print(yPred_DT)

[[ 3. 22.  1. ... 44. 45. 46.]
 [ 2.  1. 27. ... 45. 46. 47.]
 [ 3.  1. 27. ... 45. 46. 47.]
 ...
 [ 9.  1. 27. ... 45. 46. 47.]
 [ 4.  1. 27. ... 45. 46. 47.]
 [12. 27. 28. ... 45. 46. 47.]]
